### DISCUSSION TITLE
Self hosting

### DISCUSSION THREAD

**Discussion by jelupuru** [ComposioHQ/composio#1037] [Feature request]
hi team , is it possible to host composio in local server?

**Comment by appinteractive** [comment]
@composio-dev I'm also curious what's your take on that :) And awesome project!

**Comment by kinthaiofficial** [comment]
Self-hosting Composio is increasingly viable as the project has added Docker and Kubernetes support. Here's the practical setup:

**Docker Compose (quickest start)**:
```yaml
# docker-compose.yml
version: "3.8"
services:
  composio-api:
    image: composio/composio-api:latest
    ports:
      - "9900:9900"
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/composio
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=composio
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
```

**Key self-hosting considerations**:

1. **OAuth credential management**: When self-hosting, you need to register your own OAuth apps for each integration (GitHub, Slack, Google, etc.). This means going to each provider's developer console and creating an app with your self-hosted callback URL.

2. **Webhook handling**: Composio's managed service handles webhooks for you. Self-hosted means you need to expose your instance to receive webhooks from third-party services.

3. **Tool execution environment**: Some tools run code — you need a sandboxed execution environment (similar to E2B or your own container).

**Alternative: hybrid approach**:
Use Composio managed for auth/integrations but run your agent code self-hosted:
```python
import composio_openai
from openai import OpenAI

# Still connects to Composio.dev for auth, but you control the agent
client = OpenAI()
composio_client = Composio(api_key=os.environ["COMPOSIO_API_KEY"])

# Custom entity_id for your self-hosted user management
tools = composio_client.get_tools(entity_id="your-user-id", apps=["github", "slack"])
```

What's your primary motivation for self-hosting — compliance, cost, or customization?
